name: Build
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create archive
        run: |
          mkdir -p trunk/.github/files/test-plugin-update/
          cp .github/files/test-plugin-update/setup.sh trunk/.github/files/test-plugin-update/
          tar cfJ build.tar.xz trunk/
          mkdir -p zips
          touch zips/hop
      - name: Store build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jetpack-build
          path: build.tar.xz
          retention-days: 1
      - name: Create plugins artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugins
          path: zips
          retention-days: 1
