# This workflow holds jobs for linting, currently PHP and JavaScript.
#
# The jobs are all set up to only run if appropriate files have changed; the
# `changed_files` job is used to determine whether files have changed in
# various categories so the rest of the jobs can know whether to run or not.

name: Linting

on: pull_request
concurrency:
  group: linting-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_ROOT_VERSION: "dev-trunk"

jobs:
  ### Checks that lock files are up to date.
  # Local equivalent: .github/files/check-lock-files.sh
  # Note that may modify lock files in your working tree!
  lock_files:
    name: "Lock files are up to date"
    runs-on: ubuntu-latest
    needs: changed_files
    timeout-minutes: 7  # 2021-03-17: Successful runs seem to take 3+ minutes, thanks to pnpm building stuff.
    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/tool-setup

      - run: .github/files/check-lock-files.sh
