name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        default: debug
        options:
          - debug
          - trace
      dryRun:
        description: 'Dry run?'
        type: choice
        default: 'no'
        options:
          - 'no'
          - full
          - lookup
          - extract
concurrency:
  group: renovate-${{ github.ref }}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3
        with:
          path: monorepo
      - name: Move monorepo checkout to /tmp
        run: |
          mv monorepo /tmp/monorepo
          ln -s /tmp/monorepo

      - name: Determine cache key date
        id: cachedir
        run: date +date=%Y-%W >> "$GITHUB_OUTPUT"
      - name: Load cache
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/renovate-basedir
          key: renovate-${{ runner.os }}-${{ steps.cachedir.outputs.date }}
          restore-keys: renovate-${{ runner.os }}

      - name: Populate composer/pnpm caches on miss (setup tools)
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./monorepo/.github/actions/tool-setup
      - name: Populate composer/pnpm caches on miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd monorepo
          pnpm config set --location=user store-dir /tmp/renovate-basedir/cache/others/pnpm
          composer config --global cache-dir /tmp/renovate-basedir/cache/others/composer
          pnpm install
          cd projects/packages/changelogger
          composer update

      - name: Check rate limit pre-run
        env:
          TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        run: |
          curl --no-progress-meter --header "Authorization: Bearer $TOKEN" https://api.github.com/rate_limit
      - name: Fix cache permissions
        run: sudo chown -R 1000 /tmp/renovate-basedir
      - uses: renovatebot/github-action@v34.109.1
        with:
          configurationFile: /tmp/monorepo/.github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel || 'debug' }}
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun == 'no' && 'null' || github.event.inputs.dryRun || 'null' }}
          RENOVATE_BASE_DIR: /tmp/renovate-basedir
      - name: Unfix cache permissions
        run: sudo chown -R $(id -u) /tmp/renovate-basedir
      - name: Check rate limit post-run
        env:
          TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        run: |
          echo "Note any difference between this number and the one from the previous step may also include API uses from elsewhere that happened to occur at the same time."
          curl --no-progress-meter --header "Authorization: Bearer $TOKEN" https://api.github.com/rate_limit
