name: Renovate
on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run?'
        required: false
        type: boolean
concurrency:
  group: renovate-${{ github.ref }}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: monorepo
      - run: mv monorepo /tmp/monorepo
      - uses: renovatebot/github-action@v32.0.3
        with:
          configurationFile: /tmp/monorepo/.github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_DRY_RUN: ${{ github.event_name == 'push' || github.event.inputs.dryRun }}
